### ISSUE TITLE
down connection 

### ISSUE THREAD

**Issue by zkjkak** [jiangyao-scu/MEANet#1]
Hello,The baidu cloud download connection for "trained with additional 100 samples" in the salience map has failed. Could you give me a new download connection? Thank you very much。

**Comment by jiangyao-scu** [comment]
> Hello,The baidu cloud download connection for "trained with additional 100 samples" in the salience map has failed. Could you give me a new download connection? Thank you very much。

Thank you for your attention to our work. We have added another download connection (on [Google drive](https://drive.google.com/file/d/1--aNySTqR-QHi_2iO4H8B8DnPttwl2Nh/view?usp=sharing)). Hope this can help you.
